(() => {
  const E=window.CareerEngine,C=E.content,view=document.querySelector('#view'),LINK='http://127.0.0.1:43127';
  const ctx={E,C,esc:v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),stat:(a,b,c,d='')=>`<div class="metric-card ${d}"><small>${a}</small><strong>${b}</strong><span>${c}</span></div>`,health:n=>n>=85?'good':n>=60?'warn':'bad',empty:(a,b)=>`<div class="empty-state"><span>◇</span><h3>${a}</h3><p>${b}</p></div>`};
  const copy={overview:['CAREER HUB','Earn every step.','No money, licence, rating, sponsor or race car is given to you.'],inbox:['PADDOCK COMMS','Every decision arrives here.','Contracts, licensing notices and sponsor pressure.'],calendar:['SEASON CALENDAR','See the whole month.','Race weekends, tests and workshop deadlines in one calendar.'],competitions:['COMPETITION DIRECTORY','Access must be earned.','Licence, rating, safety, funding and vehicle rules decide every entry.'],teams:['DRIVER MARKET','Teams are watching the data.','Results and safety build interest; reputation alone is not enough.'],sponsors:['COMMERCIAL PADDOCK','Funding comes with pressure.','Miss objectives, lose trust and eventually lose the contract.'],garage:['PRIVATE GARAGE','Ownership comes later.','Rent early machinery, save prize money and buy cars for owner-entry series.'],driver:['DRIVER DEVELOPMENT','Rank and licence are separate.','Rating and safety unlock observed licence examinations.'],records:['CAREER ARCHIVE','Every incident changes the number.','Review rating and safety movement after every session.'],content:['AMS2 CONTENT','Build a career around what you own.','The complete source catalogue is ready.'],settings:['CAREER SETTINGS','Tune the season to your pace.','Race distance, strategy, identity and cloud career preferences.']};
  let route=location.hash.slice(1)||E.state.route||'overview',link={connected:false},cloudLink={online:false},linkSeenAt=null;
  function chrome(){const s=E.state,l=E.getLicense(),rank=E.getRank(),d=E.dateValue(),t=E.teamById(s.teamId),p=E.seriesProgress(),account=window.FBR_FIREBASE;document.querySelector('#balance-value').textContent=E.money(s.balance);document.querySelector('#license-value').textContent=l.id;document.querySelector('#license-value').style.color=l.color;document.querySelector('#weekday-value').textContent=d.toLocaleDateString('en-US',{weekday:'long'}).toUpperCase();document.querySelector('#date-value').textContent=E.formatLongDate(d);document.querySelector('#driver-name').textContent=s.profile.name;document.querySelector('#driver-team').textContent=(t?t.name:'Independent')+' · '+rank.id+' RANK';document.querySelector('#driver-initials').textContent=s.profile.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2);const accountButton=document.querySelector('#account-button');accountButton.querySelector('b').textContent=account?.user?(account.user.displayName||account.user.email||'GOOGLE ACCOUNT'):(account?.state==='loading'?'CONNECTING…':'SIGN IN');accountButton.classList.toggle('signed-in',!!account?.user);const badge=document.querySelector('#inbox-badge');badge.textContent=E.unreadCount();badge.classList.toggle('hidden',!E.unreadCount());document.querySelector('#season-percent').textContent=p+'%';document.querySelector('#season-bar').style.width=p+'%';document.querySelector('#season-week').textContent='Week '+Math.ceil((s.seasonDay+1)/7)+' of 24';document.querySelectorAll('.nav-item[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===route));const c=copy[route]||copy.overview;document.querySelector('#breadcrumb-page').textContent=route.toUpperCase();document.querySelector('#page-kicker').textContent=c[0];document.querySelector('#page-title').textContent=c[1];document.querySelector('#page-subtitle').textContent=c[2];linkChrome()}
  function render(){chrome();view.innerHTML=(window.FBR_PAGES[route]||window.FBR_PAGES.overview)(ctx)}
  function toast(type,text){const n=document.createElement('div');n.className='toast '+type;n.innerHTML=`<span>${type==='success'?'✓':type==='error'?'!':'i'}</span><p>${ctx.esc(text)}</p>`;document.querySelector('#toast-stack').appendChild(n);setTimeout(()=>n.remove(),3500)}
  function modal(html){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop" data-action="close"><div class="modal-card"><button class="modal-close" data-action="close">×</button>${html}</div></div>`}function close(){document.querySelector('#modal-root').innerHTML=''}
  function raceModal(id){const s=E.seriesById(id),e=E.entryFor(id),r=s?.rounds[e?.roundIndex];if(!r)return;if(!E.canRace(id)){toast('error','Race Control opens only on the scheduled event day');return}const rules=E.sessionRules(r),inspection=E.inspectReliability(id),vehicle={provided:'Organizer provides the vehicle',rental:'Rental vehicle reserved',owned:'Your registered vehicle required',team:'Team vehicle supplied'}[s.vehiclePolicy],car=s.vehiclePolicy==='owned'?E.registeredCarFor(s):null,condition=car?Math.round(Object.values(car.condition).reduce((a,b)=>a+b,0)/Object.keys(car.condition).length):100,reliability=inspection.applies?inspection.label:'ORGANIZER SERVICED',inspectionPanel=inspection.applies?`<div class="scrutineering-card ${inspection.cleared?'cleared':'failed'} ${inspection.level||''}"><div><span>PLAYER-ONLY SCRUTINEERING</span><strong>${inspection.cleared?'CLEARED':'INSPECTION HOLD'}</strong><small>${inspection.reason}</small></div><aside><b>${inspection.risk}%</b><em>FAILURE RISK</em></aside></div>`:`<div class="profile-notice"><strong>GLOBAL RANDOM FAILURES OFF</strong><span>Organizer, rental and team vehicles carry no private garage wear.</span></div>`;modal(`<div class="race-modal"><span class="section-kicker">ROUND ${r.round}/${r.total}</span><h2>${s.name}</h2><p>${r.layout} · ${s.className}</p><div class="session-flow-large"><div><span>P</span><strong>PRACTICE</strong><small>${r.practice} MIN</small></div><i>→</i><div><span>Q</span><strong>QUALIFYING</strong><small>${r.qualify} MIN</small></div><i>→</i><div><span>R</span><strong>RACE</strong><small>${rules.raceMinutes} MIN · ${rules.label}</small></div></div><div class="briefing-grid">${ctx.stat('VEHICLE',s.vehiclePolicy.toUpperCase(),vehicle)}${ctx.stat('WEATHER',r.weather.join(' → '),'Forecast for all sessions')}${ctx.stat('STRATEGY',rules.fuelMultiplier+'× FUEL',rules.tireMultiplier+'× tyre wear')}${ctx.stat('YOUR RELIABILITY',reliability,car?condition+'% average · '+inspection.weakest+' '+inspection.weakestValue+'%':'No private wear penalty')}</div>${inspectionPanel}${inspection.cleared?`<button class="primary-action wide" data-action="launch" data-id="${s.id}">START GAME & OPEN RACE SERVER</button><button class="secondary-action wide" data-action="result" data-id="${s.id}">ENTER COMPLETE SESSION RESULT</button>`:`<button class="danger-action wide" disabled>RACE START BLOCKED — REPAIR REQUIRED</button><button class="secondary-action wide" data-action="open-garage">OPEN GARAGE & SCHEDULE REPAIR</button>`}</div>`)};
  function resultModal(id){const s=E.seriesById(id),e=E.entryFor(id),r=s?.rounds[e?.roundIndex];if(!r)return;modal(`<form id="result-form" data-series="${id}" class="result-form"><span class="section-kicker">PRACTICE → QUALIFYING → RACE</span><h2>${r.layout}</h2><p>Clean laps build Safety. Contact, incidents and retirement can erase several clean sessions.</p><div class="form-grid"><label>FIELD SIZE<input name="fieldSize" type="number" min="2" value="20"></label><label>QUALIFY POSITION<input name="qualify" type="number" min="1" value="12"></label><label>FINISH POSITION<input name="finish" type="number" min="1" value="10"></label><label>CLEAN LAPS<input name="cleanLaps" type="number" min="0" value="5"></label><label>CONTACTS<input name="contacts" type="number" min="0" value="0"></label><label>OTHER INCIDENTS<input name="incidents" type="number" min="0" value="0"></label><label>DAMAGE %<input name="damage" type="number" min="0" max="100" value="0"></label><label class="check-label"><input name="dnf" type="checkbox"> RETIRED / DNF</label></div><button class="primary-action wide">CALCULATE OFFICIAL RESULT</button></form>`)}
  function licenseModal(){const test=E.state.pendingLicenseTest&&E.licenseTestById(E.state.pendingLicenseTest.licenseId);if(!test)return;modal(`<form id="license-form" class="result-form"><span class="section-kicker">OBSERVED LICENCE TEST</span><h2>${test.name}</h2><p>Pass standard: ${test.cleanLaps} clean laps, zero contact, no retirement and P${test.maxFinish} or better.</p><div class="form-grid"><label>FINISH POSITION<input name="finish" type="number" min="1" value="${test.maxFinish}"></label><label>CLEAN LAPS<input name="cleanLaps" type="number" min="0" value="${test.cleanLaps}"></label><label>CONTACTS<input name="contacts" type="number" min="0" value="0"></label><label class="check-label"><input name="dnf" type="checkbox"> RETIRED / DNF</label></div><button class="primary-action wide">SUBMIT OBSERVER REPORT</button></form>`)}
  function debrief(summary){const r=summary.record;modal(`<div class="rating-debrief"><span class="section-kicker">OFFICIAL DRIVER ASSESSMENT</span><h2>${r.dnf?'SESSION RETIRED':'P'+r.finish+' CLASSIFIED'}</h2><div class="rank-transition"><span style="--rank:${summary.rankBefore.color}">${summary.rankBefore.id}</span><i>→</i><span style="--rank:${summary.rankAfter.color}">${summary.rankAfter.id}</span></div><div class="debrief-scores"><article><small>RATING</small><strong class="${r.ratingDelta>=0?'good':'bad'}">${r.ratingDelta>=0?'+':''}${r.ratingDelta}</strong><span>${r.ratingBefore} → ${r.ratingAfter}</span></article><article><small>SAFETY</small><strong class="${r.safetyDelta>=0?'good':'bad'}">${r.safetyDelta>=0?'+':''}${r.safetyDelta}</strong><span>${r.safetyBefore} → ${r.safetyAfter}</span></article><article><small>CLEAN LAPS</small><strong>${r.cleanLaps||0}</strong><span>${r.contacts||0} contacts</span></article></div>${summary.sponsorOutcomes.length?`<div class="debrief-sponsors">${summary.sponsorOutcomes.map(x=>`<p class="${x.met?'good':'bad'}"><strong>${x.name}</strong><span>${x.met?'OBJECTIVE MET · '+E.money(x.bonus):'FAILED · TRUST '+x.trust}</span></p>`).join('')}</div>`:''}<button class="primary-action wide" data-action="close">CONTINUE CAREER</button></div>`)}  async function poll(){if(location.protocol==='https:'){link={connected:false};linkChrome();return}try{const r=await fetch(LINK+'/api/status',{cache:'no-store'});if(!r.ok)throw 0;link={...(await r.json()),connected:true}}catch{link={connected:false}}linkChrome()}
  function linkChrome(){const p=document.querySelector('#link-pill'),t=document.querySelector('#link-label'),m=document.querySelector('#link-monitor'),mt=document.querySelector('#link-monitor-title'),md=document.querySelector('#link-monitor-detail');if(!p)return;p.classList.remove('online','offline','warning');m?.classList.remove('online','offline','warning');let mode='offline',title='LINK APP NOT RUNNING',detail='Start FlyByRace Link for live game and telemetry connection.';if(cloudLink.online&&cloudLink.bridgeReady===true){mode='online';title=cloudLink.serverRunning?'SESSION ACTIVE':'LINK APP ONLINE';detail='Cloud heartbeat and command bridge are ready.'}else if(cloudLink.online){mode='warning';title='LINK SERVICE NOT READY';detail='The app is online but its command bridge is unavailable. Restart Link.'}else if(link.connected){mode=link.serverInstalled?'online':'warning';title=link.serverRunning?'SESSION ACTIVE':link.serverInstalled?'LINK APP ONLINE':'SERVER FOLDER MISSING';detail=link.serverInstalled?'Local connection is live and ready.':'Open Link settings and select the AMS2 Dedicated Server folder.'}p.classList.add(mode);m?.classList.add(mode);t.textContent=title;mt&&(mt.textContent=title);md&&(md.textContent=detail+(linkSeenAt?' · checked '+linkSeenAt.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):''))}
  function sessionPayload(id){const s=E.seriesById(id),e=E.entryFor(id),r=s?.rounds[e?.roundIndex];if(!s||!r)return null;const rules=E.sessionRules(r),car=s.vehiclePolicy==='owned'?E.registeredCarFor(s):null,condition=car?Math.round(Object.values(car.condition).reduce((a,b)=>a+b,0)/Object.keys(car.condition).length):100;return{id:r.id||s.id+'-r'+(e.roundIndex+1),name:s.name+' · Round '+r.round,seriesId:s.id,round:r.round,layout:r.layout,className:s.className,grid:r.grid||20,difficulty:r.difficulty||s.difficulty||80,practice:r.practice||10,qualify:r.qualify||10,race:rules.raceMinutes,hour:r.hour||14,weather:r.weather||['Clear'],damage:'FULL',randomFailures:'OFF',fuelUsage:rules.fuelUsage,tireWear:rules.tireWear,lengthPreset:rules.id,playerCarCondition:condition}}
  async function launch(id){
    const inspection=E.inspectReliability(id);
    if(!inspection.cleared){toast('error',inspection.reason||'Vehicle failed scrutineering');raceModal(id);return}
    const session=sessionPayload(id);
    if(!session){toast('error','Session profile is unavailable');return}
    modal(`<div class="launch-progress"><span class="section-kicker">FLYBYRACE LINK</span><h2>BUILDING RACE SERVER</h2><p>${session.layout} · ${session.className}</p><div class="launch-steps"><span class="active">1</span><strong>RESOLVE AMS2 CONTENT</strong><span>2</span><strong>START DEDICATED SERVER</strong><span>3</span><strong>PUBLISH ROOM</strong></div><div class="launch-spinner"></div><small>Keep FlyByRace Link running. It owns the server and will close it when Link exits.</small></div>`);
    try{
      let result;
      try{
        if(location.protocol==='https:')throw new TypeError('Use cloud bridge from secure static hosting');
        const response=await fetch(LINK+'/api/session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session})});
        result=await response.json();
        if(!response.ok){const error=new Error(result.error||'Link could not prepare the session');error.linkResponded=true;throw error}
      }catch(localError){
        if(localError.linkResponded)throw localError;
        const cloud=window.FBR_FIREBASE;
        if(!cloud?.user||!cloud.link?.online||cloud.link.bridgeReady!==true)throw new Error('FlyByRace Link is not connected. Open the installed Link app and sign in with the same Google account.');
        modal(`<div class="launch-progress"><span class="section-kicker">FIREBASE BRIDGE</span><h2>SENDING SESSION TO LINK</h2><p>${session.layout} · ${session.className}</p><div class="launch-steps"><span class="active">1</span><strong>COMMAND SENT</strong><span>2</span><strong>SERVER STARTING</strong><span>3</span><strong>ROOM PUBLISHING</strong></div><div class="launch-spinner"></div><small>The static web app is waiting for the installed Link app to confirm the room.</small></div>`);
        result=await cloud.sendLinkCommand({type:'launch-session',eventId:session.id,sessionJson:JSON.stringify(session)});
      }
      const resolved=result.resolved||{track:session.layout,vehicleClass:session.className},room=result.room||{};
      if(!/^\d{6}$/.test(String(room.number||''))||!/^\d{6}$/.test(String(room.password||'')))throw new Error('FlyByRace Link v0.6.2 or newer is required for protected race rooms.');
      const roomNumber=ctx.esc(room.number),roomPassword=ctx.esc(room.password),roomName=ctx.esc(room.name||('[FlyByRace] '+room.number));
      modal(`<div class="launch-complete"><span class="launch-check">✓</span><span class="section-kicker">PROTECTED SERVER READY</span><h2>FIND YOUR RACE ROOM</h2><p>${resolved.track||session.layout} · ${resolved.vehicleClass||session.className}</p><div class="room-credentials"><article><small>SERVER FILTER</small><strong>${roomNumber}</strong><span>${roomName}</span></article><article><small>ROOM PASSWORD</small><strong>${roomPassword}</strong><span>6-DIGIT SESSION PASSWORD</span></article></div><div class="warning-penalty"><strong>NO AMS2 RESTART REQUIRED</strong><span>Open MULTIPLAYER → BROWSE, filter by ${roomNumber}, then enter the password above. The anonymous room name contains no account or driver information.</span></div><button class="primary-action wide" data-action="close">CONTINUE</button></div>`);poll()
    }catch(error){
      modal(`<div class="launch-failed"><span class="warning-mark">!</span><span class="section-kicker">LINK COULD NOT START THE ROOM</span><h2>SESSION LAUNCH FAILED</h2><p>${ctx.esc(error.message||'FlyByRace Link is offline')}</p><div class="warning-penalty"><strong>CHECK FLYBYRACE LINK</strong><span>Open FlyByRace Link, verify both AMS2 folders and confirm the same Google account is connected.</span></div><button class="primary-action wide" data-action="close">RETURN TO RACE CONTROL</button></div>`)
    }
  }
  let timeAdvancing=false;
  const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function advanceWeek(){const current=E.dateValue(),seasonDay=E.state.seasonDay;return Array.from({length:7},(_,index)=>{const offset=index-2,date=new Date(current);date.setDate(date.getDate()+offset);const events=E.eventsOnDay(seasonDay+offset);return `<div class="advance-day ${offset===0?'is-current':''} ${offset===1?'is-next':''}"><small>${date.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}</small><strong>${String(date.getDate()).padStart(2,'0')}</strong><span>${date.toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</span><i class="${events.length?'has-event':''}"></i><em>${events.length?events.length+' EVENT'+(events.length>1?'S':''):'—'}</em></div>`}).join('')}
  async function advanceCareerDay(force=false){if(timeAdvancing)return;timeAdvancing=true;const button=document.querySelector('#advance-time'),unreadBefore=E.unreadCount(),from=E.formatLongDate(E.dateValue()),week=Math.ceil((E.state.seasonDay+1)/7),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pace=reduced?.08:1;button.disabled=true;close();const overlay=document.createElement('div');overlay.className='time-advance-overlay';overlay.innerHTML=`<div class="time-advance-shade"></div><section class="time-advance-board" role="status" aria-live="polite"><header><span class="section-kicker">CAREER TIME CONTROL</span><h2>WEEK ${String(week).padStart(2,'0')}</h2><p><b id="advance-from">${from}</b><i>→</i><strong id="advance-to">PROCESSING</strong></p></header><div class="advance-week">${advanceWeek()}</div><footer><span class="advance-loader"></span><strong id="advance-status">PROCESSING SCHEDULES, CONTRACTS & WORKSHOP</strong></footer></section>`;document.body.appendChild(overlay);requestAnimationFrame(()=>overlay.classList.add('enter'));await delay(600*pace);const outcome=E.advanceDay(force);if(outcome.blocked){overlay.remove();button.disabled=false;timeAdvancing=false;return}overlay.classList.add('advanced');overlay.querySelector('#advance-to').textContent=E.formatLongDate(E.dateValue());overlay.querySelector('#advance-status').textContent=E.unreadCount()>unreadBefore?'NEW PADDOCK MESSAGE RECEIVED':'CAREER DAY COMPLETE';await delay(1150*pace);overlay.classList.add('leave');await delay(520*pace);route='inbox';window.FBR_UI.message=E.state.inbox[0]?.id||null;E.setRoute(route);location.hash=route;render();overlay.remove();button.disabled=false;timeAdvancing=false;const newMail=Math.max(0,E.unreadCount()-unreadBefore);toast(newMail?'success':'info',newMail?newMail+' new message(s) received':'Advanced to '+E.formatLongDate(E.dateValue()))}
  document.addEventListener('click',ev=>{const go=ev.target.closest('[data-route]');if(go){ev.preventDefault();route=go.dataset.route;E.setRoute(route);location.hash=route;render();return}const el=ev.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id;
    if(a==='series'){window.FBR_UI.selectedSeries=id;route='competitions';location.hash=route;render()}
    else if(a==='select-series'){window.FBR_UI.selectedSeries=id;render()}
    else if(a==='filter'){window.FBR_UI.filter=id;render()}
    else if(a==='enter'){E.enterSeries(id);render()}
    else if(a==='withdraw'){if(confirm('Cancel this registration? Refunds fall as race day approaches.')){E.withdrawSeries(id);render()}}
    else if(a==='race'){raceModal(id)}else if(a==='result'){resultModal(id)}else if(a==='launch'){launch(id)}
    else if(a==='close'){if(ev.target===el||el.classList.contains('modal-close')||el.closest('.rating-debrief'))close()}
    else if(a==='message'){window.FBR_UI.message=id;E.markMessage(id);render()}else if(a==='archive'){E.deleteMessage(id);render()}
    else if(a==='accept-team'){E.acceptTeam(id);render()}else if(a==='leave-team'){E.leaveTeam();render()}
    else if(a==='sign-sponsor'){E.signSponsor(id);render()}else if(a==='drop-sponsor'){if(confirm('End this sponsor agreement?')){E.dropSponsor(id);render()}}
    else if(a==='repair'){E.repair(el.dataset.car,el.dataset.part);render()}
    else if(a==='buy-car'){E.buyCar(id);render()}else if(a==='sell-car'){if(confirm('Sell this vehicle?')){E.sellCar(id);render()}}
    else if(a==='license-schedule'){E.scheduleLicenseTest(id);render()}else if(a==='license-run'){licenseModal()}
    else if(a==='advance-force'){advanceCareerDay(true)}
    else if(a==='open-garage'){close();route='garage';E.setRoute(route);location.hash=route;render()}
    else if(a==='link-help'){route='settings';location.hash=route;render();poll()}
    else if(a==='calendar-prev'){window.FBR_UI.calendarOffset--;render()}else if(a==='calendar-next'){window.FBR_UI.calendarOffset++;render()}else if(a==='calendar-today'){window.FBR_UI.calendarOffset=0;render()}
    else if(a==='race-length'){E.updateSettings({raceLength:id});render()}
    else if(a==='save-profile'){E.updateProfile({name:document.querySelector('#profile-name').value.trim()||'Driver',country:document.querySelector('#profile-country').value.trim()||'Unknown',number:Number(document.querySelector('#profile-number').value)||0});toast('success','Profile saved');render()}
    else if(a==='google'){window.FBR_FIREBASE.user?window.FBR_FIREBASE.signOut():window.FBR_FIREBASE.signIn()}
    else if(a==='setup'){window.dispatchEvent(new CustomEvent('fbr:open-onboarding'))}
    else if(a==='reset'&&confirm('Reset money, rating, safety, licences, sponsors, results and vehicles to zero?')){E.resetCareer();route='overview';location.hash=route;render()}
  });
  document.addEventListener('change',ev=>{if(ev.target.matches('[data-action="dlc"]')){E.toggleDlc(ev.target.value);render()}if(ev.target.id==='discipline-filter'){window.FBR_UI.filter=ev.target.value;render()}});
  document.addEventListener('submit',ev=>{ev.preventDefault();const f=new FormData(ev.target);if(ev.target.id==='result-form'){const summary=E.recordResult(ev.target.dataset.series,{fieldSize:Number(f.get('fieldSize')),qualify:Number(f.get('qualify')),finish:Number(f.get('finish')),cleanLaps:Number(f.get('cleanLaps')),contacts:Number(f.get('contacts')),incidents:Number(f.get('incidents')),damage:Number(f.get('damage')),dnf:f.get('dnf')==='on'});if(summary)debrief(summary);render()}else if(ev.target.id==='license-form'){const summary=E.completeLicenseTest({finish:Number(f.get('finish')),cleanLaps:Number(f.get('cleanLaps')),contacts:Number(f.get('contacts')),dnf:f.get('dnf')==='on'});modal(`<div class="licence-verdict ${summary?.passed?'passed':'failed'}"><span>${summary?.passed?'✓':'×'}</span><h2>${summary?.passed?'LICENCE ISSUED':'TEST FAILED'}</h2><p>${summary?.passed?summary.test.name+' is now active.':'The observed standard was not met. Rebuild the scores and apply again.'}</p><button class="primary-action wide" data-action="close">CONTINUE</button></div>`);render()}});
  document.querySelector('#advance-time').addEventListener('click',()=>{const due=E.eventsOnDay();if(due.length){modal(`<div class="day-warning"><span class="warning-mark">!</span><span class="section-kicker">EVENTS DUE TODAY</span><h2>DO NOT MISS RACE DAY</h2><p>${due.map(x=>x.series.name+' · '+x.round.layout).join('<br>')}</p><div class="warning-penalty"><strong>Advancing now records a DNS</strong><span>Rating −60 and Safety −40 for every missed event.</span></div><button class="primary-action wide" data-action="close">RETURN TO CALENDAR</button><button class="danger-action wide" data-action="advance-force">FORFEIT & ADVANCE 1 DAY</button></div>`);return}advanceCareerDay()});document.querySelector('#link-pill').addEventListener('click',poll);document.querySelector('#link-monitor')?.addEventListener('click',()=>{route='settings';location.hash=route;render();poll()});document.querySelector('#account-button').addEventListener('click',async()=>{try{if(window.FBR_FIREBASE.user){if(confirm('Sign out of FlyByRace?'))await window.FBR_FIREBASE.signOut()}else await window.FBR_FIREBASE.signIn()}catch(e){toast('error',e.message||'Google sign-in failed')}});
  window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'overview';render()});window.addEventListener('fbr:notify',ev=>toast(ev.detail.type,ev.detail.message));window.addEventListener('fbr:account',render);window.addEventListener('fbr:state',render);window.addEventListener('fbr:link-cloud',ev=>{cloudLink=ev.detail||{online:false};linkChrome()});window.addEventListener('fbr:cloud-save',ev=>{if(ev.detail.status==='error')toast('error','Cloud save failed')});render();poll();setInterval(poll,4000);
})();