(() => {
  const CONTENT=window.FBR_CONTENT,CATALOG=window.FBR_CATALOG,SAVE_KEY='flybyrace.career.v4';
  const licenseOrder=CONTENT.licenseTests.map(x=>x.id),clone=v=>JSON.parse(JSON.stringify(v)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const RACE_LENGTH_PRESETS={short:{id:'short',label:'SHORT',description:'Fast race day, accelerated strategy',durationScale:.6,fuelUsage:4,tireWear:4,fuelMultiplier:3,tireMultiplier:3},standard:{id:'standard',label:'STANDARD',description:'Original championship distance',durationScale:1,fuelUsage:3,tireWear:3,fuelMultiplier:2,tireMultiplier:2},long:{id:'long',label:'LONG',description:'Extended distance, realistic consumption',durationScale:1.75,fuelUsage:2,tireWear:2,fuelMultiplier:1,tireMultiplier:1}};
  const isoDate=d=>d.toISOString().slice(0,10),initialInbox=()=>[
    {id:'academy-welcome',from:'FlyByRace Academy',subject:'Choose your academy path',date:'01 APR',type:'license',unread:true,body:'You have no licence, rating, budget or race car. Four free academies provide the machinery: karting, formula, touring car and road car. Register for one and attend on the scheduled day.'},
    {id:'rookie-guide',from:'Driver Development',subject:'Nothing is given here',date:'01 APR',type:'news',unread:true,body:'Teams and sponsors will ignore an unknown driver. Finish the academy, earn a licence, rent machinery and build a record before expecting an offer.'}
  ];
  const defaultState=()=>({
    version:4,profile:{name:'Young Kim',country:'Korea',number:77},date:'2026-04-01',season:1,seasonDay:0,
    onboarding:{completed:false,step:0,gameSettingsConfirmed:false},balance:0,rating:0,safety:0,reputation:0,route:'overview',
    licenses:[],academy:{completed:false,completedIds:[]},pendingLicenseTest:null,licenseResults:[],
    disciplineRep:{grassroots:0,formula:0,touring:0,gt:0,prototype:0,endurance:0,offroad:0,historic:0},
    skills:{pace:0,consistency:0,racecraft:0,wet:0,mechanical:0,fitness:0},
    teamId:null,teamOffers:[],sponsors:[],ownedDlc:['Base Game'],
    entries:[],
    inbox:initialInbox(),results:[],trophies:[],unlockedAchievements:[],garage:[],repairs:[],reliabilityChecks:{},
    activity:[{date:'2026-04-01',text:'Career created — choose a rookie academy'}],
    settings:{currency:'USD',difficultyOffset:0,autosave:true,weatherRealism:true,randomFailures:false,raceLength:'standard'}
  });
  function scheduleFor(series,startDay=state?.seasonDay||0){
    const first=series.rounds[0]?.dateOffset||0,lead=series.registrationLead??3;
    return series.rounds.map(round=>startDay+lead+Math.max(0,(round.dateOffset||0)-first));
  }
  function normalizeState(value){
    const d=defaultState();
    if(!value)return d;
    const base={...d,...value,version:4,profile:{...d.profile,...(value.profile||{})},onboarding:{...d.onboarding,...(value.onboarding||{})},settings:{...d.settings,...(value.settings||{}),currency:'USD',randomFailures:false,raceLength:RACE_LENGTH_PRESETS[value.settings?.raceLength]?.id||'standard'},academy:{...d.academy,...(value.academy||{}),completedIds:[...(value.academy?.completedIds||[])]},ownedDlc:Array.from(new Set(['Base Game',...(value.ownedDlc||[])])),licenses:Array.isArray(value.licenses)?value.licenses:[],sponsors:Array.isArray(value.sponsors)?value.sponsors:[],garage:Array.isArray(value.garage)?value.garage:[],entries:Array.isArray(value.entries)?value.entries:[],reliabilityChecks:value.reliabilityChecks&&typeof value.reliabilityChecks==='object'?value.reliabilityChecks:{}};
    base.entries=base.entries.map(old=>{
      const seriesId=old.seriesId==='flybyrace-driver-academy'?'flybyrace-kart-academy':old.seriesId;
      const series=CONTENT.championships.find(x=>x.id===seriesId);
      if(!series)return null;
      const entry={...old,seriesId,registeredDay:old.registeredDay??base.seasonDay,paid:old.paid??0};
      if(!Array.isArray(entry.roundDays))entry.roundDays=scheduleFor(series,base.seasonDay+1-(series.registrationLead??3));
      return entry;
    }).filter(Boolean);
    return base;
  }
  function load(){try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem('flybyrace.career.v3')||localStorage.getItem('flybyrace.career.v2'));return normalizeState(v)}catch{return defaultState()}}
  let state=load();const listeners=new Set();
  function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));listeners.forEach(fn=>fn(state));window.dispatchEvent(new CustomEvent('fbr:state',{detail:state}))}
  function replaceState(next,source='external'){state=normalizeState(clone(next));localStorage.setItem(SAVE_KEY,JSON.stringify(state));listeners.forEach(fn=>fn(state));window.dispatchEvent(new CustomEvent('fbr:state',{detail:{state,source}}))}
  function notify(type,message,detail={}){window.dispatchEvent(new CustomEvent('fbr:notify',{detail:{type,message,...detail}}))}
  function getRank(value=state.rating){return CONTENT.rankTiers.reduce((r,t)=>value>=t.min?t:r,CONTENT.rankTiers[0])}
  function getLicense(){const id=[...licenseOrder].reverse().find(x=>state.licenses.includes(x));return CONTENT.licenses.find(x=>x.id===id)||{id:'—',name:'Unlicensed',color:'#667180',description:'Complete the academy and pass the Rookie Permit test'}}
  function licenseAllows(required){if(required==='ACADEMY')return true;const current=licenseOrder.indexOf(getLicense().id),needed=licenseOrder.indexOf(required);return current>=needed&&needed>=0}
  function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0)}
  function raceLengthPreset(){return RACE_LENGTH_PRESETS[state.settings.raceLength]||RACE_LENGTH_PRESETS.standard}
  function sessionRules(round){const preset=raceLengthPreset(),base=Math.max(1,Number(round?.raceMinutes)||20),scaled=Math.max(5,Math.ceil(base*preset.durationScale/5)*5);return{...preset,raceMinutes:scaled}}
  function updateSettings(patch){const next={...state.settings,...patch};next.raceLength=RACE_LENGTH_PRESETS[next.raceLength]?.id||'standard';next.randomFailures=false;state.settings=next;persist();notify('success','Race format updated: '+RACE_LENGTH_PRESETS[next.raceLength].label);return state.settings}

  function dateValue(){return new Date(state.date+'T12:00:00')}function daysUntil(offset){return offset-state.seasonDay}
  function seriesById(id){return CONTENT.championships.find(x=>x.id===id)}function entryFor(id){return state.entries.find(x=>x.seriesId===id)}
  function teamById(id){return CONTENT.teams.find(x=>x.id===id)}function sponsorById(id){return CONTENT.sponsors.find(x=>x.id===id)}
  function sponsorContract(id){return state.sponsors.find(x=>x.id===id)}
  function requiredDlcs(series){const out=new Set(),cars=CATALOG.cars.filter(x=>x.className===series.className);if(cars.length&&!cars.some(x=>x.dlc==='Base Game'))cars.forEach(x=>out.add(x.dlc));series.rounds.forEach(r=>{const t=CATALOG.tracks.find(x=>x.layout===r.layout);if(t&&t.dlc!=='Base Game')out.add(t.dlc)});return [...out]}
  function vehicleRequirementText(series){
    if(series.vehiclePolicy==='provided')return 'Organizer-provided vehicle';
    if(series.vehiclePolicy==='rental')return 'Rental included';
    if(series.vehiclePolicy==='team')return 'Team vehicle required';
    const req=series.vehicleRequirement;
    return req?.type==='model'?'Exact model: '+req.label:'Owned class: '+(req?.label||series.className);
  }
  function carMatchesSeries(car,series){const req=series.vehicleRequirement;return req?.type==='model'?car.catalogId===req.value:car.className===(req?.value||series.className)}
  function registeredCarFor(series){return state.garage.find(car=>carMatchesSeries(car,series))}
  function ownedCarFor(series){const car=registeredCarFor(series);return car?.status==='READY'?car:null}
  function vehicleReliability(car){if(!car)return{average:0,weakest:'none',weakestValue:0,risk:100,level:'blocked',label:'NO VEHICLE',mandatory:true};const parts=Object.entries(car.condition).sort((a,b)=>a[1]-b[1]),[weakest,weakestValue]=parts[0],average=Math.round(parts.reduce((sum,[,value])=>sum+value,0)/parts.length),base=weakestValue>=90?0:weakestValue>=80?3:weakestValue>=70?7:weakestValue>=55?15:weakestValue>=40?30:weakestValue>=25?55:100,criticalCount=parts.filter(([,value])=>value<50).length,risk=clamp(base+(base<100?Math.max(0,criticalCount-1)*5:0),0,100),level=risk===0?'clear':risk<15?'watch':risk<40?'warning':risk<100?'critical':'blocked',label={clear:'FACTORY CLEAR',watch:'MONITOR',warning:'HIGH RISK',critical:'CRITICAL',blocked:'UNSAFE'}[level];return{average,weakest,weakestValue,risk,level,label,mandatory:risk===100}}
  function reliabilitySignature(car){return Object.entries(car.condition).sort(([a],[b])=>a.localeCompare(b)).map(([part,value])=>part+':'+value).join('|')}
  function reliabilityRoll(seed){let hash=2166136261;for(let i=0;i<seed.length;i++){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619)}return(Math.abs(hash>>>0)%100)+1}
  function invalidateReliability(carId){Object.keys(state.reliabilityChecks).forEach(key=>{if(state.reliabilityChecks[key]?.carId===carId)delete state.reliabilityChecks[key]})}
  function inspectReliability(seriesId){const series=seriesById(seriesId),entry=entryFor(seriesId),round=series?.rounds[entry?.roundIndex];if(!series||!round)return{applies:false,cleared:false,reason:'Session entry not found'};if(series.vehiclePolicy!=='owned')return{applies:false,cleared:true,risk:0,label:'ORGANIZER SERVICED',reason:'No player-owned reliability check'};const car=registeredCarFor(series);if(!car)return{applies:true,cleared:false,risk:100,label:'NO VEHICLE',reason:'The registered owner-entry vehicle is unavailable'};const profile=vehicleReliability(car);if(car.status==='WORKSHOP')return{...profile,applies:true,cleared:false,carId:car.id,reason:'Vehicle is still in the workshop'};const key=seriesId+':'+entry.roundIndex+':'+car.id,signature=reliabilitySignature(car),cached=state.reliabilityChecks[key];if(cached?.signature===signature)return cached;const roll=reliabilityRoll(key+'|'+signature+'|S'+state.season),failed=profile.mandatory||roll<=profile.risk,result={...profile,key,signature,carId:car.id,seriesId,round:round.round,checkedAt:state.date,roll,applies:true,cleared:!failed,reason:failed?(profile.mandatory?profile.weakest.toUpperCase()+' below scrutineering minimum':profile.weakest.toUpperCase()+' reliability inspection failed'):'Pre-race scrutineering cleared'};state.reliabilityChecks[key]=result;if(failed){car.status='INSPECTION HOLD';mail('Technical Scrutineering',car.name+' placed on inspection hold',result.reason+'. Repair the '+profile.weakest+' before this vehicle can be cleared for another inspection.','garage');state.activity.unshift({date:state.date,text:'Inspection hold: '+car.name+' '+profile.weakest})}else if(car.status==='INSPECTION HOLD')car.status='READY';persist();return result}
  function entryCost(series){return (series.entryFee||0)+(series.rentalFee||0)}
  function vehicleAccess(series){if(['provided','rental','team'].includes(series.vehiclePolicy))return true;return !!ownedCarFor(series)}
  function eligibility(series){const reasons=[];if(series.academy&&(state.academy.completedIds||[]).includes(series.id))reasons.push('This academy is already completed');if(!series.academy&&!licenseAllows(series.license))reasons.push('Licence '+series.license+' required');if(state.rating<(series.ratingRequired||0))reasons.push('Rating '+series.ratingRequired+' required');if(state.safety<(series.safetyRequired||0))reasons.push('Safety '+series.safetyRequired+' required');if(series.teamRequired&&!state.teamId)reasons.push('Team contract required');const missing=requiredDlcs(series).filter(x=>!state.ownedDlc.includes(x));if(missing.length)reasons.push('Missing DLC: '+missing.join(', '));if(!vehicleAccess(series))reasons.push(vehicleRequirementText(series));if(state.balance<entryCost(series)&&!state.teamId)reasons.push('Insufficient funds: '+money(entryCost(series)));return{eligible:!reasons.length,reasons,missingDlcs:missing}}
  function enterSeries(id){const s=seriesById(id);if(!s)return false;if(entryFor(id)){notify('info','Already registered for '+s.name);return false}const check=eligibility(s);if(!check.eligible){notify('error',check.reasons[0]);return false}const paid=state.teamId?0:entryCost(s);state.balance-=paid;const roundDays=scheduleFor(s,state.seasonDay);state.entries.push({seriesId:id,roundIndex:0,points:0,position:null,status:'entered',registeredDay:state.seasonDay,paid,roundDays});mail('Competition Office','Registration confirmed: '+s.name,'Your entry is accepted. Round 1 is scheduled for '+dateFromSeasonDay(roundDays[0])+'. '+vehicleRequirementText(s)+'.','race');state.activity.unshift({date:state.date,text:'Registered for '+s.name});persist();notify('success','Registered — first event in '+(roundDays[0]-state.seasonDay)+' day(s)');return true}
  function withdrawSeries(id){const entry=entryFor(id),series=seriesById(id);if(!entry||!series||entry.status==='completed')return false;const days=(entry.roundDays?.[entry.roundIndex]??state.seasonDay)-state.seasonDay;const refund=entry.roundIndex===0&&days>1?Math.round((entry.paid||0)*.75):entry.roundIndex===0&&days>0?Math.round((entry.paid||0)*.25):0;state.balance+=refund;state.entries=state.entries.filter(x=>x!==entry);mail('Competition Office','Entry cancelled: '+series.name,'Your registration has been cancelled. Refund: '+money(refund)+'.','race');state.activity.unshift({date:state.date,text:'Cancelled '+series.name+' entry'});persist();notify('info','Entry cancelled'+(refund?' — '+money(refund)+' refunded':' — no refund'));return{refund}}
  function mail(from,subject,body,type='news'){state.inbox.unshift({id:'mail-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),from,subject,date:formatShortDate(dateValue()),type,unread:true,body})}
  function dateFromSeasonDay(day){const d=dateValue();d.setDate(d.getDate()+day-state.seasonDay);return formatLongDate(d)}
  function eventDay(entry){return entry.roundDays?.[entry.roundIndex]}
  function eventsOnDay(day=state.seasonDay){return state.entries.map(entry=>{const series=seriesById(entry.seriesId),round=series?.rounds[entry.roundIndex];return series&&round&&entry.status==='entered'&&eventDay(entry)===day?{series,round,entry,day}:null}).filter(Boolean)}
  function canRace(id){const entry=entryFor(id);return !!entry&&entry.status==='entered'&&eventDay(entry)===state.seasonDay}
  function advanceDay(force=false){
    const due=eventsOnDay();
    if(due.length&&!force)return{blocked:true,events:due};
    if(force)due.forEach(({series,round,entry})=>{entry.roundIndex++;entry.position=null;if(entry.roundIndex>=series.rounds.length)entry.status=series.academy?'failed':'completed';state.safety=clamp(state.safety-40,0,1000);state.rating=Math.max(0,state.rating-60);state.results.unshift({id:'dns-'+Date.now()+'-'+round.round,seriesId:series.id,round:round.round,layout:round.layout,date:state.date,qualify:null,finish:null,dnf:true,dns:true,damage:0,cleanLaps:0,contacts:0,points:0,prize:0,sponsorBonus:0,safetyDelta:-40,ratingDelta:-60});mail('Race Control','DNS recorded: '+series.name,'You advanced past '+round.layout+' without competing. A DNS and rating penalties were applied.','result')});
    if(force)state.entries=state.entries.filter(entry=>entry.status!=='failed');
    const d=dateValue();d.setDate(d.getDate()+1);state.date=isoDate(d);state.seasonDay++;state.repairs.forEach(x=>x.daysRemaining--);state.repairs.filter(x=>x.daysRemaining<=0).forEach(job=>{const car=state.garage.find(x=>x.id===job.carId);if(car){car.condition[job.part]=100;invalidateReliability(car.id);mail('Workshop',car.name+' repair completed','The '+job.part+' work is complete. Reinspection is available once all workshop jobs finish.','garage')}});state.repairs=state.repairs.filter(x=>x.daysRemaining>0);state.garage.forEach(car=>{if(car.status==='WORKSHOP'&&!state.repairs.some(job=>job.carId===car.id))car.status='READY'});state.activity.unshift({date:state.date,text:'Advanced to '+formatLongDate(d)});persist();return{blocked:false,forfeited:due}
  }
  function markMessage(id){const m=state.inbox.find(x=>x.id===id);if(m){m.unread=false;persist()}}function deleteMessage(id){state.inbox=state.inbox.filter(x=>x.id!==id);persist()}
  function acceptTeam(id){const t=teamById(id);if(!t||!state.teamOffers.includes(id)){notify('error','No contract offer from this team');return false}if(!licenseAllows(t.license)){notify('error','Licence '+t.license+' required');return false}state.teamId=id;state.teamOffers=[];mail(t.name,'Contract signed','The team provides scheduled machinery and covers eligible championship entry costs.','offer');persist();notify('success','Signed with '+t.name);return true}
  function leaveTeam(){const t=teamById(state.teamId);state.teamId=null;persist();notify('info','Contract ended'+(t?' with '+t.name:''))}  function sponsorRequirements(s){return{rating:300+s.prestige*20,safety:Math.min(900,180+s.prestige*7),license:s.prestige<25?'R':s.prestige<55?'D':s.prestige<80?'C':'B'}}
  function sponsorEligibility(s){const q=sponsorRequirements(s),reasons=[];if(!licenseAllows(q.license))reasons.push('Licence '+q.license+' required');if(state.rating<q.rating)reasons.push('Rating '+q.rating+' required');if(state.safety<q.safety)reasons.push('Safety '+q.safety+' required');if(state.sponsors.length>=2)reasons.push('Maximum two partners');return{eligible:!reasons.length,reasons,...q}}
  function signSponsor(id){const s=sponsorById(id);if(!s||sponsorContract(id))return false;const q=sponsorEligibility(s);if(!q.eligible){notify('error',q.reasons[0]);return false}state.sponsors.push({id,trust:65,failures:0,races:0});state.balance+=Math.round(s.signingBonus*.35);mail(s.name,'Conditional partnership signed','Trust begins at 65. Miss race objectives and the brand will issue warnings before terminating the agreement.','offer');persist();notify('success','Signed conditional deal with '+s.name);return true}
  function dropSponsor(id){const s=sponsorById(id);state.sponsors=state.sponsors.filter(x=>x.id!==id);mail(s?.name||'Commercial Office','Partnership ended','The sponsorship agreement has been terminated by the driver.','offer');persist()}
  function sponsorObjectiveMet(s,result){const o=s.objective.toLowerCase(),n=Number((o.match(/(\d+)/)||[])[1]||10);if(o.includes('clean laps'))return result.cleanLaps>=n;if(o.includes('qualify'))return result.qualify<=n;if(o.includes('without major damage'))return !result.dnf&&result.damage<=15;if(o.includes('complete'))return !result.dnf;if(o.includes('podium'))return !result.dnf&&result.finish<=3;if(o.includes('win'))return !result.dnf&&result.finish===1;return !result.dnf&&result.finish<=n}
  function processSponsors(result){const outcomes=[];for(const contract of [...state.sponsors]){const s=sponsorById(contract.id);if(!s)continue;contract.races++;const met=sponsorObjectiveMet(s,result);let bonus=0;if(met){contract.trust=clamp(contract.trust+10,0,100);contract.failures=Math.max(0,contract.failures-1);bonus=Math.round(s.signingBonus*.07)}else{const loss=result.dnf?40:25;contract.trust=clamp(contract.trust-loss,0,100);contract.failures++;if(contract.trust<=0){mail(s.name,'Partnership terminated','Repeated missed objectives exhausted our trust. The contract is terminated immediately.','offer');state.sponsors=state.sponsors.filter(x=>x!==contract)}else mail(s.name,contract.trust<=30?'Final warning: deliver now':'Objective missed','You failed: '+s.objective+'. Brand trust fell by '+loss+' to '+contract.trust+'. '+(contract.trust<=30?'Another failure may terminate the deal.':''),'offer')}outcomes.push({id:s.id,name:s.name,met,trust:contract.trust,bonus})}return outcomes}
  function licenseTestById(id){return CONTENT.licenseTests.find(x=>x.id===id)}
  function licenseEligibility(id){const t=licenseTestById(id),reasons=[];if(!t)return{eligible:false,reasons:['Unknown test']};if(state.licenses.includes(id))reasons.push('Licence already earned');if(t.id==='R'&&!state.academy.completed)reasons.push('Complete the Driver Academy');if(t.previous&&!state.licenses.includes(t.previous))reasons.push('Licence '+t.previous+' required');if(state.safety<t.safety)reasons.push('Safety '+t.safety+' required');if(state.rating<t.rating)reasons.push('Rating '+t.rating+' required');if(state.balance<t.fee)reasons.push('Test fee '+money(t.fee)+' required');if(state.pendingLicenseTest)reasons.push('Another test is scheduled');return{eligible:!reasons.length,reasons,test:t}}
  function scheduleLicenseTest(id){const q=licenseEligibility(id);if(!q.eligible){notify('error',q.reasons[0]);return false}state.balance-=q.test.fee;state.pendingLicenseTest={licenseId:id,scheduledAt:state.date};mail('Licensing Office',q.test.name+' test scheduled','Required: '+q.test.cleanLaps+' clean laps, no contact, no retirement and finish P'+q.test.maxFinish+' or better.','license');persist();notify('success',q.test.name+' test scheduled');return true}
  function completeLicenseTest(result){const pending=state.pendingLicenseTest;if(!pending)return null;const t=licenseTestById(pending.licenseId),passed=!result.dnf&&result.contacts===0&&result.cleanLaps>=t.cleanLaps&&result.finish<=t.maxFinish,safetyDelta=passed?20:-35,ratingDelta=passed?30:-50;state.safety=clamp(state.safety+safetyDelta,0,1000);state.rating=Math.max(0,state.rating+ratingDelta);state.pendingLicenseTest=null;state.licenseResults.unshift({date:state.date,licenseId:t.id,passed,...result});if(passed){state.licenses.push(t.id);mail('Licensing Office',t.name+' issued','You passed the observed assessment. Licence '+t.id+' championships are now available.','license');notify('success',t.name+' earned')}else{mail('Licensing Office',t.name+' test failed','The test standard was not met. Build your scores and apply again. The fee is not refunded.','license');notify('error','Licence test failed')}persist();return{passed,test:t,safetyDelta,ratingDelta}}  function carMarket(){return CONTENT.carMarket}
  function buyCar(id){const item=CONTENT.carMarket.find(x=>x.id===id);if(!item)return false;if(!licenseAllows(item.license)){notify('error','Licence '+item.license+' required');return false}if(!state.ownedDlc.includes(item.dlc)){notify('error','Missing DLC: '+item.dlc);return false}if(state.balance<item.price){notify('error','Insufficient funds');return false}if(state.garage.some(x=>x.catalogId===id)){notify('info','Vehicle already owned');return false}state.balance-=item.price;state.garage.push({id:'owned-'+Date.now(),catalogId:id,name:item.name,className:item.className,ownership:'OWNED',value:item.price,mileage:0,status:'READY',condition:{engine:100,gearbox:100,suspension:100,brakes:100,body:100}});mail('Vehicle Registry',item.name+' registered','The vehicle is now eligible for owner-entry championships in '+item.className+'.','garage');persist();notify('success',item.name+' purchased');return true}
  function sellCar(id){const car=state.garage.find(x=>x.id===id);if(!car)return;const price=Math.round(car.value*.65);state.balance+=price;state.garage=state.garage.filter(x=>x!==car);state.repairs=state.repairs.filter(x=>x.carId!==id);invalidateReliability(id);persist();notify('success',car.name+' sold for '+money(price))}
  function repair(carId,part){const car=state.garage.find(x=>x.id===carId);if(!car||car.condition[part]>=100)return;if(state.repairs.some(x=>x.carId===carId&&x.part===part)){notify('info','Repair already scheduled');return}const wear=100-car.condition[part],base={engine:35,gearbox:26,suspension:19,brakes:12,body:9}[part]||15,cost=Math.ceil(wear*base),days=Math.max(1,Math.ceil(wear/8));if(state.balance<cost){notify('error','Insufficient workshop budget');return}state.balance-=cost;state.repairs.push({carId,part,cost,daysRemaining:days});car.status='WORKSHOP';invalidateReliability(carId);persist();notify('success',part+' repair scheduled · '+days+' days')}
  function scoreResult(result){const clean=Math.max(0,result.cleanLaps||0),contacts=Math.max(0,result.contacts||0),incidents=Math.max(0,result.incidents||0),field=Math.max(result.finish||1,result.fieldSize||20),safetyDelta=clean*5-contacts*45-incidents*20-Math.floor((result.damage||0)/10)*4-(result.dnf?80:0),base=(field+1-(result.finish||field))*4-Math.round(field*1.5),qualifying=Math.max(0,field-(result.qualify||field)),ratingDelta=result.dnf?-90:base+Math.round(qualifying*.8);return{safetyDelta,ratingDelta}}
  function maybeTeamOffer(){if(state.teamId||state.teamOffers.length||!state.licenses.includes('R')||state.rating<300)return;const team=CONTENT.teams.find(x=>licenseAllows(x.license));if(team){state.teamOffers=[team.id];mail(team.name,'Driver evaluation invitation','Your recent rating and safety record meet our first scouting threshold. A conditional team offer is available.','offer')}}  function recordResult(seriesId,result){
    const entry=entryFor(seriesId),series=seriesById(seriesId);if(!entry||!series)return null;if(!canRace(seriesId)){notify('error','This event can only be raced on its scheduled day');return null;}
    const round=series.rounds[entry.roundIndex],rankBefore=getRank(),safetyBefore=state.safety,ratingBefore=state.rating,pointsTable=[25,18,15,12,10,8,6,4,2,1],points=result.dnf?0:(pointsTable[result.finish-1]||0);
    entry.points+=points;entry.roundIndex++;entry.position=result.finish;if(entry.roundIndex>=series.rounds.length)entry.status='completed';
    const prize=series.academy?0:result.finish===1?series.roundPrize:result.finish<=3?Math.round(series.roundPrize*.65):result.finish<=10?Math.round(series.roundPrize*.25):0,score=scoreResult(result),sponsorOutcomes=series.academy?[]:processSponsors(result),sponsorBonus=sponsorOutcomes.reduce((n,x)=>n+x.bonus,0);
    state.safety=clamp(state.safety+score.safetyDelta,0,1000);state.rating=Math.max(0,state.rating+score.ratingDelta);state.reputation=Math.floor(state.rating/25);state.balance+=prize+sponsorBonus;
    state.disciplineRep[series.discipline]=Math.max(0,(state.disciplineRep[series.discipline]||0)+Math.max(1,12-result.finish));state.skills.pace=clamp(state.skills.pace+Math.max(0,6-result.finish),0,100);state.skills.consistency=clamp(state.skills.consistency+Math.min(3,result.cleanLaps||0),0,100);
    if(series.academy&&entry.status==='completed'){state.academy.completed=true;state.academy.completedIds=Array.from(new Set([...(state.academy.completedIds||[]),series.id]));mail('FlyByRace Academy','Academy programme complete','Your observed sessions are complete. Meet the rating and safety thresholds to schedule the Rookie Permit test.','license')}
    const car=series.vehiclePolicy==='owned'?ownedCarFor(series):null;if(car){const actualMinutes=sessionRules(round).raceMinutes,durationWear=Math.max(1,Math.round(actualMinutes/20));car.mileage+=Math.round(actualMinutes*2.1);car.condition.engine=clamp(car.condition.engine-(durationWear+Math.round(result.damage/12)),0,100);car.condition.gearbox=clamp(car.condition.gearbox-durationWear,0,100);car.condition.brakes=clamp(car.condition.brakes-(durationWear+1),0,100);car.condition.body=clamp(car.condition.body-result.damage,0,100)}
    const rankAfter=getRank(),record={id:'result-'+Date.now(),seriesId,round:round.round,layout:round.layout,date:state.date,qualify:result.qualify,finish:result.finish,dnf:result.dnf,damage:result.damage,cleanLaps:result.cleanLaps,contacts:result.contacts,points,prize,sponsorBonus,safetyBefore,safetyAfter:state.safety,safetyDelta:state.safety-safetyBefore,ratingBefore,ratingAfter:state.rating,ratingDelta:state.rating-ratingBefore,rankBefore:rankBefore.id,rankAfter:rankAfter.id};
    state.results.unshift(record);mail('Race Control','Official result: '+(result.dnf?'DNF':'P'+result.finish)+' at '+round.layout,'Rating '+(record.ratingDelta>=0?'+':'')+record.ratingDelta+', Safety '+(record.safetyDelta>=0?'+':'')+record.safetyDelta+'. '+points+' championship points and '+money(prize+sponsorBonus)+' credited.','result');maybeTeamOffer();persist();notify('success','Result recorded · '+rankAfter.id+' rank');return{record,rankBefore,rankAfter,sponsorOutcomes}
  }
  function toggleDlc(name){if(name==='Base Game')return;state.ownedDlc=state.ownedDlc.includes(name)?state.ownedDlc.filter(x=>x!==name):[...state.ownedDlc,name];persist()}
  function resetCareer(){const old=state,fresh=defaultState();fresh.profile=clone(old.profile);fresh.onboarding=clone(old.onboarding);fresh.ownedDlc=clone(old.ownedDlc);fresh.settings=clone(old.settings);state=fresh;persist();notify('success','Career reset to zero')}
  function updateProfile(patch){state.profile={...state.profile,...patch};persist()}function updateOnboarding(patch){state.onboarding={...state.onboarding,...patch};persist()}
  function formatShortDate(d){return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}).toUpperCase()}function formatLongDate(d){return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}
  function unreadCount(){return state.inbox.filter(x=>x.unread).length}
  function nextEvent(){const candidates=[];state.entries.forEach(entry=>{const series=seriesById(entry.seriesId),round=series&&series.rounds[entry.roundIndex],day=eventDay(entry);if(round&&Number.isFinite(day))candidates.push({series,round,entry,day,days:day-state.seasonDay,date:dateFromSeasonDay(day)})});return candidates.sort((a,b)=>a.day-b.day)[0]||null}
  function seriesProgress(){return Math.min(100,Math.round(state.seasonDay/(24*7)*100))}function setRoute(route){state.route=route;persist()}function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
  window.CareerEngine={get state(){return state},version:4,content:CONTENT,catalog:CATALOG,save:persist,replaceState,subscribe,getRank,getLicense,licenseAllows,money,raceLengthPreset,sessionRules,updateSettings,seriesById,entryFor,teamById,sponsorById,sponsorContract,sponsorEligibility,requiredDlcs,entryCost,vehicleRequirementText,registeredCarFor,ownedCarFor,vehicleReliability,inspectReliability,vehicleAccess,eligibility,enterSeries,withdrawSeries,eventsOnDay,canRace,eventDay,dateFromSeasonDay,advanceDay,markMessage,deleteMessage,acceptTeam,leaveTeam,signSponsor,dropSponsor,licenseTestById,licenseEligibility,scheduleLicenseTest,completeLicenseTest,carMarket,buyCar,sellCar,repair,recordResult,toggleDlc,resetCareer,updateProfile,updateOnboarding,unreadCount,nextEvent,seriesProgress,setRoute,formatLongDate,dateValue};
})();